/**
 * Shared Gemini API client with model fallback logic.
 */

import { GoogleGenAI } from '@google/genai';

const genai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

// Model preference order — first that succeeds wins
const MODELS = [
    'gemini-3.1-flash-lite-preview',
    'gemini-2.5-flash-lite',
];

/**
 * Generate content with automatic model fallback.
 * Tries models in preference order; returns result + metadata.
 *
 * @param {string} prompt - The user prompt
 * @param {string} systemInstruction - System instruction for the model
 * @param {string} tag - Logging tag (e.g. 'tldr', 'all-tldr')
 * @returns {Promise<{ text: string, model: string, isFallback: boolean }>}
 */
export async function generateWithFallback(prompt, systemInstruction, tag = 'gemini') {
    const config = {
        contents: prompt,
        config: {
            systemInstruction,
            serviceTier: 'standard',
        },
    };

    let lastError;
    for (let i = 0; i < MODELS.length; i++) {
        const model = MODELS[i];
        try {
            const result = await genai.models.generateContent({ model, ...config });
            return {
                text: result.text,
                model,
                isFallback: i > 0,
            };
        } catch (err) {
            lastError = err;
            console.log(`[${tag}] Model ${model} failed (${err.message?.slice(0, 80)}), trying next...`);
        }
    }

    // All models failed
    throw lastError;
}

/** Fallback note to append when a non-primary model was used. */
export const FALLBACK_NOTE = '\n\n*🤖 The clanker slaves were busy — this summary was generated by the backup model.*';
