/**
 * Shared Gemini API client with model fallback logic.
 */

import { GoogleGenAI } from '@google/genai';
import { TLDR_MODELS } from '../config/models.js';

const genai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

/**
 * Generate content with automatic model fallback.
 * Tries models in preference order; returns result + metadata.
 *
 * @param {string} prompt - The user prompt
 * @param {string} systemInstruction - System instruction for the model
 * @param {string} tag - Logging tag (e.g. 'tldr', 'all-tldr')
 * @param {string[]} [models] - Model fallback chain (defaults to TLDR_MODELS)
 * @returns {Promise<{ text: string, model: string, isFallback: boolean }>}
 */
export async function generateWithFallback(prompt, systemInstruction, tag = 'gemini', models = TLDR_MODELS) {
    const config = {
        contents: prompt,
        config: {
            systemInstruction,
            serviceTier: 'standard',
        },
    };

    let lastError;
    for (let i = 0; i < models.length; i++) {
        const model = models[i];
        try {
            const result = await genai.models.generateContent({ model, ...config });
            const usage = result.usageMetadata || {};
            console.log(`[${tag}] tokens — input: ${usage.promptTokenCount ?? '?'}, output: ${usage.candidatesTokenCount ?? '?'}, total: ${usage.totalTokenCount ?? '?'} (model: ${model})`);
            return {
                text: result.text,
                model,
                isFallback: i > 0,
                tokens: {
                    input: usage.promptTokenCount ?? 0,
                    output: usage.candidatesTokenCount ?? 0,
                    total: usage.totalTokenCount ?? 0,
                },
            };
        } catch (err) {
            lastError = err;
            console.log(`[${tag}] Model ${model} failed (${err.message?.slice(0, 80)}), trying next...`);
        }
    }

    // All models failed
    throw lastError;
}

/** Fallback note to append when a non-primary model was used. */
export const FALLBACK_NOTE = '\n\n*🤖 The clanker slaves were busy — this summary was generated by the backup model.*';
